### PR TITLE
[RFC] Implement changes to allow embedding the webapp

### PR DESCRIPTION
**Pull request by maxatdetroit**
## Part of CityOfDetroit/data-engineering#2668, CityOfDetroit/detroitmi#1759

Generally speaking, we have to make additional changes to prepare this webapp to be embedded on an existing website, HTML document, and browser.

## Changes in this PR

1. Remove the duplicate use of `html` and `body` elements
2. Remove the use of `main` (since an existing website/webpage would already have a `main` element)
3. Create an option for the application to use in-memory page routing instead of browser-URL page routing
4. Create a separate build process for the in-memory page routing (used for embedding the webapp) and browser-URL page routing (used for hosting the web app as a standalone website)

This approach addresses the problem we saw in CityOfDetroit/detroitmi#1775. Here's a screenshot of the webapp rendered on detroitmi.gov:

base-unit-success-detroitmigov

There is some more work (see section below) to make it styled exactly the same as the netlify deployed version but it's functional. 

The standalone version also continues to work well (tested with `npm run serve`).

## Questions

1. Once we move the tool onto detroitmi.gov, will there even be a need to support the standalone deployment, or should I remove that in favor of just the embedded version on this PR?

## Remaining Work

1. We'll need to encapsulate the styles of the base unit tools web app inside of a [Shadow DOM](https://javascript.info/shadow-dom) to avoid the styles of detroitmi.gov affecting the web app and vice-versa.

### CODE REVIEW

**Comment by maxatdetroit** [comment]
@jmcbroom @manuelnelson I listed out the changes in this PR that we would have to make to get this webapp fully ready for deployment on detroitmi.gov. I also left a question for you.

P.S. I highly recommend ignoring commit 627aed6b3b63d1 (here's a [link to this PR without it](https://github.com/CityOfDetroit/base-unit-tools/pull/53/files/3f9c519531867e7c712ac2782f3193200d769289)) while reviewing the changes. That commit is just moving all the build files into separate directories.

**Comment by maxatdetroit** [comment]
Oh it also looks like my build changes broke the automated netlify deployment. I can fix those, but going to leave them broken for now while we discuss the direction of this PR and the question in the first comment.

**Comment by jmcbroom** [comment]
> Oh it also looks like my build changes broke the automated netlify deployment. I can fix those, but going to leave them broken for now while we discuss the direction of this PR and the question in the first comment.

no worries on this -- it's just a deploy preview (any PR into `main` generates one)

**Comment by maxatdetroit** [comment]
Thanks @jmcbroom . Let me know what you think about the question below and the general approach of this PR.

> Once we move the tool onto detroitmi.gov, will there even be a need to support the standalone deployment, or should I remove that in favor of just the embedded version on this PR?

**Comment by jmcbroom** [comment]
> Thanks @jmcbroom . Let me know what you think about the question below and the general approach of this PR.

> Once we move the tool onto detroitmi.gov, will there even be a need to support the standalone deployment, or should I remove that in favor of just the embedded version on this PR?

Hey -- everything looks good to me. I would say we don't need to support the standalone deployment -- once we have it working well on detroitmi.gov I will set up a redirect from the netlify subdomain back to detroitmi.gov URL!

**Review by jmcbroom — APPROVED** [review]

**Pull request merged**
